/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resources;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maurice Ramsbottom
 */
public class CareersGUI extends javax.swing.JPanel {

    /**
     * Creates new form CareersGUI
     */
    public CareersGUI() {
        initComponents();
           
    }//need to keep method here or browser will not open properly?
        public static void openWebpage(URI uri) {
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelMaths = new javax.swing.JPanel();
        scrollMaths = new javax.swing.JScrollPane();
        txtMaths = new javax.swing.JTextArea();
        btnMaths = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtScience = new javax.swing.JTextArea();
        btnScience = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEng = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTech = new javax.swing.JTextArea();
        btnTech = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Careers");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtMaths.setEditable(false);
        txtMaths.setColumns(20);
        txtMaths.setLineWrap(true);
        txtMaths.setRows(5);
        txtMaths.setText("As Maths is such a concentrated subject, there are numerous career paths that can be followed on with a degree/masters qualification. From teaching at second level/university level to Aerospace Engineering, one can see there is great potential to be unlocked in the subject.");
        txtMaths.setWrapStyleWord(true);
        scrollMaths.setViewportView(txtMaths);

        btnMaths.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMaths.setText("See More Information");
        btnMaths.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMathsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMathsLayout = new javax.swing.GroupLayout(panelMaths);
        panelMaths.setLayout(panelMathsLayout);
        panelMathsLayout.setHorizontalGroup(
            panelMathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMathsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollMaths, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMathsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMaths)))
                .addContainerGap())
        );
        panelMathsLayout.setVerticalGroup(
            panelMathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMathsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaths)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maths", panelMaths);

        txtScience.setEditable(false);
        txtScience.setColumns(20);
        txtScience.setLineWrap(true);
        txtScience.setRows(5);
        txtScience.setText("Science is a broad and exciting subject and can be studied in a huge range of sub-categories. Biological Sciences like Molecular Biology, Medicinal Chemistry, Geological Science, Theoretical Physics are only some of the areas of study available to Irish Students. ");
        txtScience.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtScience);

        btnScience.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnScience.setText("See More Information");
        btnScience.setMaximumSize(new java.awt.Dimension(181, 75));
        btnScience.setMinimumSize(new java.awt.Dimension(181, 75));
        btnScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScienceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnScience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Science", jPanel2);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Engineering is defined as the branch of science and technology concerned with the design, building, and use of engines, machines, and structures. Again, there are a huge range of careers to choose from including Mechnical Engineering, Structural Engineering and Aeronautical Engineering. If you like to understand how things work and are interested in designing/building then a career in Engineering is for you.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        btnEng.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEng.setText("See More Information");
        btnEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEng)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEng)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Engineering", jPanel3);

        txtTech.setEditable(false);
        txtTech.setColumns(20);
        txtTech.setLineWrap(true);
        txtTech.setRows(5);
        txtTech.setText("Technology is relied on heavily in day to day, modern life. With the fast pace in research and advancement of technology, there are many careers to choose from. Science related and Maths related careers have a cross over into the Tech field.");
        txtTech.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtTech);

        btnTech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTech.setText("See More Information");
        btnTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTech)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTech)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Technology", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMathsActionPerformed
        // TODO add your handling code here:
        //try catch statement 
        try {   //hyperlink for more info on courses in each section
                Desktop.getDesktop().browse(new URL("http://gradireland.com/careers-advice/jobs-with-your-degree/your-degree-in-mathematics").toURI());
                      }                
          catch (IOException ex) {
                    Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
                } catch (URISyntaxException ex) {
            Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnMathsActionPerformed

    private void btnScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScienceActionPerformed
        // TODO add your handling code here:
          try {
                Desktop.getDesktop().browse(new URL("http://gradireland.com/careers-sectors/science-research-and-development/careers-for-science-graduates-in-ireland").toURI());
                      }                
            catch (IOException ex) {
                    Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
                } catch (URISyntaxException ex) {
            Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnScienceActionPerformed

    private void btnEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngActionPerformed
        // TODO add your handling code here:
         try {
              Desktop.getDesktop().browse(new URL("http://gradireland.com/career-sectors/engineering").toURI());
                      }
            catch (IOException ex) {
                    Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
                } catch (URISyntaxException ex) {
            Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEngActionPerformed

    private void btnTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTechActionPerformed
        // TODO add your handling code here:
        try {
              Desktop.getDesktop().browse(new URL("http://www.careercast.com/jobs-rated/12-best-engineering-information-technology-jobs").toURI());
                      }
            catch (IOException ex) {
                    Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
                } catch (URISyntaxException ex) {
            Logger.getLogger(CareersGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btnTechActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEng;
    private javax.swing.JButton btnMaths;
    private javax.swing.JButton btnScience;
    private javax.swing.JButton btnTech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelMaths;
    private javax.swing.JScrollPane scrollMaths;
    private javax.swing.JTextArea txtMaths;
    private javax.swing.JTextArea txtScience;
    private javax.swing.JTextArea txtTech;
    // End of variables declaration//GEN-END:variables
}