/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resources;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maurice
 */
public class EduGUI extends javax.swing.JPanel {
     //arrays declared
    
    private final String[] uniLinks; 
    private final String[] itLinks;
    private final String[] onlineLinks;
    

    /**
     * Creates new form EdGUI
     */
    public EduGUI() {
        initComponents();
        //initialize arrays     
        this.uniLinks = new String[]{"http://www.ncirl.ie/courses/", 
                                     "http://www.dcu.ie/studentrecruitment/undergraduate-listing.shtml", 
                                     "http://www.tcd.ie/study/", 
                                     "http://www.ucd.ie/prospectivestudents/",
                                     "http://www.ucc.ie/en/study/",
                                     "http://www.maynoothuniversity.ie/study-maynooth/"};
        this.itLinks = new String[]{"http://www.dit.ie/study/",
                                    "http://www.lit.ie/Courses/Pages/CAO%20Courses.aspx",
                                    "http://www.itb.ie/StudyatITB/index.html",
                                    "http://www.gmit.ie/courses/all-courses", 
                                    "http://www.cit.ie/study_at_CIT",
                                    "http://www.itcarlow.ie/study-at-itc/full-time-courses.htm",};
        this.onlineLinks = new String[]{"http://www.udemy.com","http://www.coursera.com",};
        //initialise method
        LoadLinks();
    }
            //use default browser when opening URL
    public static void openWebpage(URI uri) {
    
    
}

    public void LoadLinks(){
        /*display each array as a loop inside respective comboboxes*/
        int i;
        for(i=0; i<uniLinks.length; i++){
            comboUni.addItem(uniLinks[i]);            
            String uniLinks=comboUni.getSelectedItem().toString();
        }
        int j;
        for(j=0; j<itLinks.length; j++){
            comboIt.addItem(itLinks[j]);
            String itLinks=comboIt.getSelectedItem().toString();
        }
        
        int k;
        for(k=0; k<onlineLinks.length; k++){
            comboOnline.addItem(onlineLinks[k]);

            String onlineLinks=comboOnline.getSelectedItem().toString();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUni = new javax.swing.JLabel();
        lblIts = new javax.swing.JLabel();
        lblOnline = new javax.swing.JLabel();
        comboUni = new javax.swing.JComboBox();
        comboIt = new javax.swing.JComboBox();
        comboOnline = new javax.swing.JComboBox();
        btnGoUni = new javax.swing.JButton();
        btnGoIt = new javax.swing.JButton();
        btnGoOnline = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Education");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_hat.png"))); // NOI18N
        jLabel2.setToolTipText("");

        lblUni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUni.setText("Universities");

        lblIts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIts.setText("Institutes of Technology");

        lblOnline.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOnline.setText("Online Courses");

        comboUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUniActionPerformed(evt);
            }
        });

        comboIt.setModel(comboIt.getModel());
        comboIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItActionPerformed(evt);
            }
        });

        comboOnline.setModel(comboOnline.getModel());
        comboOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOnlineActionPerformed(evt);
            }
        });

        btnGoUni.setText("GO!");
        btnGoUni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoUniActionPerformed(evt);
            }
        });

        btnGoIt.setText("GO!");
        btnGoIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoItActionPerformed(evt);
            }
        });

        btnGoOnline.setText("GO!");
        btnGoOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoOnlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUni)
                    .addComponent(lblIts)
                    .addComponent(lblOnline)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboUni, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboIt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGoIt)
                    .addComponent(btnGoOnline)
                    .addComponent(btnGoUni)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUni)
                    .addComponent(comboUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoUni))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIts)
                    .addComponent(comboIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoIt))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOnline)
                    .addComponent(comboOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoOnline))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUniActionPerformed
        //comboUni uses uniLinks array for internet query
        String uniItems=comboUni.getSelectedItem().toString();
    
    }//GEN-LAST:event_comboUniActionPerformed

    private void btnGoUniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoUniActionPerformed
        // TODO add your handling code here:
        //try catch for open desktop and use string in array as URL
                  try {
                      try {
                          Desktop.getDesktop().browse(new URI(comboUni.getSelectedItem().toString()));
                      } catch (URISyntaxException ex) {
                          Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
                      }
            }   
            catch (IOException ex) {
                    Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
                }

    }//GEN-LAST:event_btnGoUniActionPerformed

    private void btnGoOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoOnlineActionPerformed
        // TODO add your handling code here:
              try {
                  Desktop.getDesktop().browse(new URI(comboOnline.getSelectedItem().toString()));
              } catch (URISyntaxException ex) {
                  Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
       
    catch (IOException ex) {
            Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
        } 
    }//GEN-LAST:event_btnGoOnlineActionPerformed

    private void btnGoItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoItActionPerformed
        // TODO add your handling code here:
              try {
                  Desktop.getDesktop().browse(new URI(comboIt.getSelectedItem().toString()));
              } catch (URISyntaxException ex) {
                  Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
              }   
    catch (IOException ex) {
            Logger.getLogger(EduGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"ERROR IO EXCEPTION");
        }
    }//GEN-LAST:event_btnGoItActionPerformed

    private void comboItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItActionPerformed
        // TODO add your handling code here:
        //comboIt uses uniLinks array for internet query
        String itLinks=comboIt.getSelectedItem().toString();
    }//GEN-LAST:event_comboItActionPerformed

    private void comboOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOnlineActionPerformed
        // TODO add your handling code here:
        //comboOnline uses uniLinks array for internet query
        String onlineLinks=comboOnline.getSelectedItem().toString();
    }//GEN-LAST:event_comboOnlineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoIt;
    private javax.swing.JButton btnGoOnline;
    private javax.swing.JButton btnGoUni;
    private javax.swing.JComboBox comboIt;
    private javax.swing.JComboBox comboOnline;
    private javax.swing.JComboBox comboUni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIts;
    private javax.swing.JLabel lblOnline;
    private javax.swing.JLabel lblUni;
    // End of variables declaration//GEN-END:variables

   
}
