/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resources;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author klasecki
 */
public class ULinksAddGUI extends javax.swing.JPanel {
    private ArrayList <Link> linkList;
    /**
     * Creates new form ULinksAddGUI
     */
    public ULinksAddGUI() {
        initComponents();
        linkList = new ArrayList <Link>();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFname = new javax.swing.JTextField();
        LBname = new javax.swing.JLabel();
        CBsubject = new javax.swing.JComboBox();
        LBsubject = new javax.swing.JLabel();
        LBurl = new javax.swing.JLabel();
        TFurl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFdesc = new javax.swing.JTextArea();
        LBdesc = new javax.swing.JLabel();
        BTsave = new javax.swing.JButton();

        LBname.setText("Name:");

        CBsubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Math", "Sience", "Enineering" }));

        LBsubject.setText("Subject");

        LBurl.setText("URL:");

        TFdesc.setColumns(20);
        TFdesc.setRows(5);
        jScrollPane1.setViewportView(TFdesc);

        LBdesc.setText("Description:");

        BTsave.setText("Save");
        BTsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTsave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBname)
                            .addComponent(LBsubject)
                            .addComponent(LBurl)
                            .addComponent(LBdesc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFname)
                            .addComponent(TFurl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBname)
                    .addComponent(TFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBsubject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBurl)
                    .addComponent(TFurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBdesc))
                .addGap(18, 18, 18)
                .addComponent(BTsave)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveFile () {
        File outFile;
        FileOutputStream foStream;
        ObjectOutputStream ooStream;
        //Use a try statement
        try{
            //creat objects
            outFile = new File("flinks.dat");
            foStream = new FileOutputStream(outFile);
            ooStream = new ObjectOutputStream(foStream);
            //write arrayList to file
            ooStream.writeObject(linkList);
            //close stream
            ooStream.close();
        }
        //catch the IOException
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void readFile () {
        
        File inFile;
        FileInputStream fiStream;
        ObjectInputStream oiStream;
        //use a try statement
        try{
            //create objects
            inFile = new File("flinks.dat");
            fiStream = new FileInputStream(inFile);
            oiStream = new ObjectInputStream(fiStream);
            //read arrayList from file
            linkList = (ArrayList <Link>)oiStream.readObject();
            //loop through the ArrayList
            
        }
        //catch IOException
        catch(IOException e){
            System.out.println(e);
        }
        //catch classNotFoundException
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }
    
    
    private void BTsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsaveActionPerformed
        
        Link l = new Link();
      
        readFile ();
        
            l.setName(TFname.getText());
            l.setSubject(CBsubject.getSelectedItem().toString());
            l.setLink(TFurl.getText());
            l.setDecr(TFdesc.getText());
       
        
        linkList.add(l);

        saveFile ();
        JOptionPane.showMessageDialog(null, "Link has been added.");
           TFname.setText("");
           TFurl.setText("");
           TFdesc.setText("");
    }//GEN-LAST:event_BTsaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTsave;
    private javax.swing.JComboBox CBsubject;
    private javax.swing.JLabel LBdesc;
    private javax.swing.JLabel LBname;
    private javax.swing.JLabel LBsubject;
    private javax.swing.JLabel LBurl;
    private javax.swing.JTextArea TFdesc;
    private javax.swing.JTextField TFname;
    private javax.swing.JTextField TFurl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
