/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assesments;

import Login.User;
import SQL.Connect;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;



/**
 *
 * @author Deniss
 */
public class AFrame extends javax.swing.JFrame {
    //CREATING OBJECT USER LATTER INJECTING VALUES FROM OTHER CLASS
    User user = new User();
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    private String subject;
    private int questionCount;
    private int status = 0;

    //Just if no owerloaded parametres
    public AFrame() {
        initComponents();
        //FILLING COMBO BOXES
        LoadLists();
        //Setting this so that all programm wouldn't close on x click
        //Owerriding
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //Setting Location of the JFORM
        int w = this.getSize().width;
        int h = this.getSize().height;
       int x = (dim.width/2)-w;
        int y = (dim.height/4)-h;
        // Move the window
        this.setLocation(x, y);
    }


//Second constructor(OVERLOADED)
       public AFrame(int status,String subject,int questionCount, User usr) {
           this.user = usr;
           this.subject = subject;
           this.questionCount = questionCount;
           this.status = status;
           initComponents();
           //FILLING COMBO BOXES
           LoadLists();
        //Setting this so that all programm wouldn't close on x click
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        //Setting Location
        int w = this.getSize().width;
        int h = this.getSize().height;
       int x = (dim.width/2)-w;
        int y = (dim.height/4)-h;
        // Move the window
        this.setLocation(x, y);
        CheckStatus();
    }

    
    //ONCLICK In Menu LOADING EXAM JPANEL
       public void ExamGuiLoad(){
        this.status = status;
        MFrame.removeAll();
        //Resizing Frame For the exam
        this.setSize(380,540);
        //Instanciating new JPanel in the JForm
        ExamGui  myExamGui = new ExamGui(subject,questionCount);
        myExamGui.setVisible(true);
        myExamGui.setSize(380, 520);
        myExamGui.setUser(user);
        MFrame.add(myExamGui);
        MFrame.repaint(); 
    }
       //method not necesarry
    //public void SetUser(){
           // LblUser.setText("You are logged in as: "+ user.getLogin());
      // }
               
    //THIS PART IS FOR UPPER MENUES ON mainGui CHECKS WHICH IS Ass Type Chosen
    public void CheckStatus(){
        if(status==2){
            ExamGuiLoad(); 
        }
        else if(status==1){
            QuizGuiLoad();          
        }

    }
    //LOADING if clicked in menu QUIZ JPANEL
    public void QuizGuiLoad(){
        MFrame.removeAll();
        //Resizing Frame For the quiz
        this.setSize(380,540);
        //Setting subject
        QuizGui  myQuizGui = new QuizGui(subject,questionCount);
        myQuizGui.setVisible(true);
        myQuizGui.setSize(380, 520);
        myQuizGui.setUser(user);
        MFrame.add(myQuizGui);
        MFrame.repaint();
    }
    
    public void LoadLists(){
        //QUESTION NUMBER GENERATION
        ComboQuestion.removeAllItems();
        for(int num = 20; num>=5; num = num -1){
        ComboQuestion.addItem(num);
    }
        //KAMILS System for filling combo box 
        ComboSubject.removeAllItems();
        Connection con = Connect.ConnectDB();
        ResultSet rs = null;
        PreparedStatement pst = null;
     
    //CONNECTING TO DATABASE, THEN MAKING QUERY
     try {
        //Making query so that result set would get only unique subject without duplicates
        String sql = "SELECT DISTINCT Subject FROM QuizQuestions";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        //looping while there are entries found in DB
        while(rs.next()) {
           String c  = rs.getString("Subject");
           ComboSubject.addItem(c);
        }  
    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }

       public void setUser(User usr){
        this.user = usr;
        //SetUser();
        LblUser.setText("You are logged in as: "+ user.getLogin());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl2 = new javax.swing.JLabel();
        MFrame = new javax.swing.JPanel();
        BtnQuiz = new javax.swing.JButton();
        BtnExam = new javax.swing.JButton();
        Lbl1 = new javax.swing.JLabel();
        ComboSubject = new javax.swing.JComboBox();
        LblTopic = new javax.swing.JLabel();
        LblTopic1 = new javax.swing.JLabel();
        ComboQuestion = new javax.swing.JComboBox();
        BtnExit = new javax.swing.JButton();
        LblUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();

        Lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assesments/icon1.png"))); // NOI18N
        Lbl2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MFrame.setLayout(null);

        BtnQuiz.setText("Quiz");
        BtnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuizActionPerformed(evt);
            }
        });
        MFrame.add(BtnQuiz);
        BtnQuiz.setBounds(300, 310, 70, 23);

        BtnExam.setText("Exam");
        BtnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExamActionPerformed(evt);
            }
        });
        MFrame.add(BtnExam);
        BtnExam.setBounds(210, 310, 70, 23);

        Lbl1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        Lbl1.setText("Assesments section");
        MFrame.add(Lbl1);
        Lbl1.setBounds(30, 30, 314, 46);

        ComboSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSubjectActionPerformed(evt);
            }
        });
        MFrame.add(ComboSubject);
        ComboSubject.setBounds(250, 220, 100, 20);

        LblTopic.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        LblTopic.setText("Number of Questions:");
        MFrame.add(LblTopic);
        LblTopic.setBounds(220, 240, 130, 20);

        LblTopic1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        LblTopic1.setText("Chose Your Topic:");
        MFrame.add(LblTopic1);
        LblTopic1.setBounds(230, 190, 130, 30);

        ComboQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MFrame.add(ComboQuestion);
        ComboQuestion.setBounds(300, 270, 56, 20);

        BtnExit.setText("Assesment Results");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        MFrame.add(BtnExit);
        BtnExit.setBounds(20, 310, 160, 23);

        LblUser.setText("You are logged in as: ######");
        MFrame.add(LblUser);
        LblUser.setBounds(20, 280, 170, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 2, 14)); // NOI18N
        jLabel1.setText("START HERE:");
        MFrame.add(jLabel1);
        jLabel1.setBounds(250, 140, 90, 20);

        Lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assesments/icon1.png"))); // NOI18N
        Lbl3.setText("jLabel2");
        MFrame.add(Lbl3);
        Lbl3.setBounds(0, 0, 380, 350);

        getContentPane().add(MFrame);
        MFrame.setBounds(0, 0, 380, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getComboSubject() {
        return ComboSubject;
    }

    private void BtnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuizActionPerformed
           subject = (String)ComboSubject.getSelectedItem();
           questionCount = (int)ComboQuestion.getSelectedItem();
            QuizGuiLoad();
    }//GEN-LAST:event_BtnQuizActionPerformed

    private void BtnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExamActionPerformed
           subject = (String)ComboSubject.getSelectedItem();
           questionCount = (int)ComboQuestion.getSelectedItem();
            ExamGuiLoad();      // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExamActionPerformed

    private void ComboSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSubjectActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
         this.setVisible(false);
         ResultsTable myResultsTable  = new ResultsTable();
        myResultsTable.setVisible(true);
        myResultsTable.setSize(800, 575);
        myResultsTable.setResizable(false);
        myResultsTable.setUser(user);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AFrame().setVisible(true);

            }
        });
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExam;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnQuiz;
    private javax.swing.JComboBox ComboQuestion;
    private javax.swing.JComboBox ComboSubject;
    private javax.swing.JLabel Lbl1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel LblTopic;
    private javax.swing.JLabel LblTopic1;
    private javax.swing.JLabel LblUser;
    private javax.swing.JPanel MFrame;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
