/*
 *FAQScrollGui.java
 */
package FAQ;

import javax.swing.JOptionPane;

/**
 *
 * @author Maurice Ramsbottom
 */
public class FAQScrollGui extends javax.swing.JPanel {

    /**
     * Creates new form FAQScrollGui
     */
    public FAQScrollGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpFAQ = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblInstructions = new javax.swing.JLabel();
        checkQ1 = new javax.swing.JCheckBox();
        btnSubmitFAQ = new javax.swing.JButton();
        checkQ2 = new javax.swing.JCheckBox();
        checkQ3 = new javax.swing.JCheckBox();
        checkQ4 = new javax.swing.JCheckBox();
        checkQ5 = new javax.swing.JCheckBox();
        checkQ6 = new javax.swing.JCheckBox();
        checkQ7 = new javax.swing.JCheckBox();
        checkQ8 = new javax.swing.JCheckBox();
        lblQmark = new javax.swing.JLabel();

        lblInstructions.setText("Select ONE question by clicking on the check box, then clicking submit.");
        lblInstructions.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        grpFAQ.add(checkQ1);
        checkQ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ1.setSelected(true);
        checkQ1.setText("1. Why is Mathematics an important field of study? ");
        checkQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQ1ActionPerformed(evt);
            }
        });

        btnSubmitFAQ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSubmitFAQ.setText("Submit ");
        btnSubmitFAQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitFAQMouseClicked(evt);
            }
        });
        btnSubmitFAQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitFAQActionPerformed(evt);
            }
        });

        grpFAQ.add(checkQ2);
        checkQ2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ2.setText("2. How can studying Science benefit my career choice? ");

        grpFAQ.add(checkQ3);
        checkQ3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ3.setText("3. What kind of Institutions are there to cater for these fields of study?");

        grpFAQ.add(checkQ4);
        checkQ4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ4.setText("4. Why is it that Ireland attracts a lot of big technology companies to her shores?");
        checkQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQ4ActionPerformed(evt);
            }
        });

        grpFAQ.add(checkQ5);
        checkQ5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ5.setText("5. What is Computer Science and why should I study it? ");

        grpFAQ.add(checkQ6);
        checkQ6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ6.setText("6. Can Computer Science teach me how to develop video games?");
        checkQ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQ6ActionPerformed(evt);
            }
        });

        grpFAQ.add(checkQ7);
        checkQ7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ7.setText("7. What types of new technologies are changing the industry?");

        grpFAQ.add(checkQ8);
        checkQ8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkQ8.setText("8. What kind of funding can I get to aid my studies?");

        lblQmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FAQ/rsz_qmark2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkQ8)
                        .addGap(82, 82, 82)
                        .addComponent(btnSubmitFAQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(186, 186, 186))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkQ3)
                            .addComponent(checkQ4)
                            .addComponent(checkQ2)
                            .addComponent(lblInstructions)
                            .addComponent(checkQ1)
                            .addComponent(checkQ5)
                            .addComponent(checkQ6)
                            .addComponent(checkQ7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblQmark)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(checkQ2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQmark)
                        .addGap(18, 18, 18)
                        .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkQ1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(checkQ8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSubmitFAQ, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkQ1ActionPerformed

    private void btnSubmitFAQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitFAQMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitFAQMouseClicked
    //On pressing Submit, the selection statement kicks in on the checkbox group and displays the appropriate answer
    private void btnSubmitFAQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitFAQActionPerformed
        // TODO add your handling code here:
        if(checkQ1.isSelected()){
            JOptionPane.showMessageDialog(null,"Mathematics is an extremely important subject. \n"
                + "Music, Physics, Engineering, Computer Science and Engineering all have a basis in Mathematic principles. \n"
                + "Did you know: An entire compsition in Music can be completed using only Mathematics?");
        }
       else if(checkQ2.isSelected()){
            JOptionPane.showMessageDialog(null,"Science has advanced in leaps and bounds in the past century. \n"
                + "Technology Companies and Medical/Pharmaceutical Companies are investing millions in research and development \n"
                + "which in turn creates a demand for qualified and educated minds in a Science related subject.");
        }
       else if(checkQ3.isSelected()){
            JOptionPane.showMessageDialog(null,"Ireland has a high standard of Education Institutions ranging from Universities \n"
                + "to Institutes of Technology. Each College/University has an assortment of courses available to \n"
                + "prospective students looking to further their education. In recent times there has been a focus \n"
                + "on Maths, Science and Technology courses.");
        }
       else if(checkQ4.isSelected()){
            JOptionPane.showMessageDialog(null,"There is a simple answer to that: Temperate Climate. One of the biggest challenges facing \n"
                + "Chip Manufacturers and companies like Google, Yahoo, Paypal is the heat generated by their data centers. Like your \n"
                + "home P.C., a data center needs to stay cool to operate efficiently. Ireland is an ideal location, with a climate \n"
                + "that's not too hot or too cold!");
        }
       else if(checkQ5.isSelected()){
            JOptionPane.showMessageDialog(null,"Computer Science is more than just programming, it is about designing complex software, \n"
                + "the analysis of complex problems, design and implementation of programming languages, the design of effective interfaces\n"
                + "and much much more. For a person who wishes to work in a job, for which technology is an asset, Computer Science is \n"
                + "hugely beneficial in terms of developing the skills necessary to do the job. ");
        }
       else if(checkQ6.isSelected()){
            JOptionPane.showMessageDialog(null,"While video game development relys on some of the fundamentals of Computer Science, \n"
                + "there is more to it than meets the eye. A skilled mathematician for example, with an eye for design would be \n"
                + "better suited in a career such as a games developer. That being said, a degree in Computer Science would still \n"
                + "be great preparation to enter into the industry. ");
        }
       else if(checkQ7.isSelected()){
            JOptionPane.showMessageDialog(null,"In recent years, Cloud Computing has taken a huge step forward and has brought great  \n"
                + "benefits to e-commerce, data management and user experience. Companies now look to the cloud for storage, "
                + "development, web hosting, and can rely heavily on it.\n"
                + "Mobile has advanced in leaps and bounds with the market seeing huge revenue being generated by applications \n"
                + "and massive competition between rival companies such as Samsung, Apple, HTC etc. Application design and \n"
                + "development is an ever growing business. ");
        }
       else if(checkQ8.isSelected()){
            JOptionPane.showMessageDialog(null,"Depending on a number of criteria including but not limited to your age, marital status\n"
                + " and income, certain funding may be available to you to aid you with your studies. For more information see www.citizensinformation.ie\n"
                + " and also www.susi.ie");
           
       
       }
       else{
           JOptionPane.showMessageDialog(null,"That is not a valid selection");
            }
      
         
                
    }//GEN-LAST:event_btnSubmitFAQActionPerformed

    private void checkQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkQ4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkQ4ActionPerformed

    private void checkQ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkQ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkQ6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitFAQ;
    private javax.swing.JCheckBox checkQ1;
    private javax.swing.JCheckBox checkQ2;
    private javax.swing.JCheckBox checkQ3;
    private javax.swing.JCheckBox checkQ4;
    private javax.swing.JCheckBox checkQ5;
    private javax.swing.JCheckBox checkQ6;
    private javax.swing.JCheckBox checkQ7;
    private javax.swing.JCheckBox checkQ8;
    private javax.swing.ButtonGroup grpFAQ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblQmark;
    // End of variables declaration//GEN-END:variables
}
